//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartItem
    {
        public int itemID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> variationID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cartID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> unitCost { get; set; }
        public Nullable<decimal> total { get; set; }
        public string imagePath { get; set; }
        public string orderID { get; set; }
    }
    public class CombinedCartUser
    {
        public List<cartItem> listCartItems { get; set; }
        public eWallet eWallet { get; set; }
        public order order { get; set; }
    }
}
