//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mssdbModel : DbContext
    {
        public mssdbModel()
            : base("name=mssdbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrators { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<cartItem> cartItems { get; set; }
        public virtual DbSet<eWallet> eWallets { get; set; }
        public virtual DbSet<orderLine> orderLines { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orderShippingInfo> orderShippingInfoes { get; set; }
        public virtual DbSet<pointLine> pointLines { get; set; }
        public virtual DbSet<productCategory> productCategories { get; set; }
        public virtual DbSet<productCategoryLine> productCategoryLines { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productVariation> productVariations { get; set; }
        public virtual DbSet<transactionHistoryOrder> transactionHistoryOrders { get; set; }
        public virtual DbSet<transactionHistoryWallet> transactionHistoryWallets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userRole> userRoles { get; set; }
    }
}
