//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderShippingInfo
    {
        public string shippingID { get; set; }
        public string type { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string address { get; set; }
        public Nullable<int> poscode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> branchID { get; set; }
        public Nullable<bool> isPickup { get; set; }
        public string orderID { get; set; }
        public string name { get; set; }
    }
}
