//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class order
    {
        [Key]
        [DisplayName("Order ID")]
        public int orderID { get; set; }
        [DisplayName("Created Date Time")]
        public Nullable<System.DateTime> createdDT { get; set; }
        [DisplayName("Shipped Date Time")]
        public Nullable<System.DateTime> shippedDT { get; set; }
        [DisplayName("Purchaser ID")]
        public Nullable<int> userID { get; set; }
        [DisplayName("Status")]
        public string status { get; set; }
        public Nullable<int> shippingID { get; set; }
        public Nullable<int> pointRedeemed { get; set; }
        public Nullable<decimal> amountPaid { get; set; }
        public string consignment { get; set; }
    }
}
