//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderID { get; set; }
        public Nullable<System.DateTime> createdDT { get; set; }
        public Nullable<System.DateTime> shippedDT { get; set; }
        public Nullable<int> userID { get; set; }
        public string status { get; set; }
        public Nullable<int> shippingID { get; set; }
        public Nullable<int> pointRedeemed { get; set; }
        public Nullable<decimal> amountPaid { get; set; }
        public string consignment { get; set; }
    }
}
