//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEXMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pointLine
    {
        public int pointID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> transactionDT { get; set; }
        public string referenceID { get; set; }
        public Nullable<int> adminID { get; set; }
    }
}
